### ISSUE TITLE
API key use in Android app

### ISSUE THREAD

**Issue by mg6maciej** [googlesamples/android-play-safetynet#5]
In the documentation (https://developer.android.com/training/safetynet/attestation.html#add-api-key) it is suggested to use API key, but this sample doesn't use it and does not mention its use in client app. In this repo use of API key is only mentioned when doing online verification on the server, which is also mentioned in the documentation.

So the question is if this API key should be used or should not be used in Android app? Also found it [unanswered on StackOverflow](https://stackoverflow.com/questions/43095289/is-api-key-needed-in-safetynet-attestation/).

**Comment by jfschmakeit** [comment]
Hi,
Sorry, only just saw this question. 

The latest Google Play Services SDK actually requires an API key as part of the call to the <a href="https://developers.google.com/android/reference/com/google/android/gms/safetynet/SafetyNetClient.html#attest(byte[], java.lang.String)">attest() function</a>.
We have just updated the Android sample code to include an API key and we'll be updating the documentation shortly as well.

**Comment by mg6maciej** [comment]
What would be the reason to require it in client? How would you stop someone from getting the key from compiled APK and using it to do verify (https://www.googleapis.com/androidcheck/v1/attestations/verify) requests on my behalf?

**Comment by gkasireddy202** [comment]
I have a API key for google maps can i use that API key for safetynet.?



Thanks.
